"""Generate a Homebrew formula from the verified source archive and runtime lock."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import tomllib
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]


def runtime_resources(root: Path = ROOT) -> list[dict]:
    exported = subprocess.run(
        [
            "uv",
            "export",
            "--no-cache",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
            "--no-header",
            "--no-annotate",
        ],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    packages = tomllib.loads((root / "uv.lock").read_text())["package"]
    selected = []
    for line in exported.splitlines():
        if not line.strip():
            continue
        requirement = Requirement(line)
        supported = []
        for platform, system in (("darwin", "Darwin"), ("linux", "Linux")):
            for machine in ("arm64", "x86_64", "aarch64"):
                environment = default_environment() | {
                    "sys_platform": platform,
                    "platform_system": system,
                    "platform_machine": machine,
                    "python_version": "3.13",
                    "python_full_version": "3.13.0",
                    "extra": "",
                }
                supported.append(not requirement.marker or requirement.marker.evaluate(environment))
        if not any(supported):
            continue
        if not all(supported):
            raise ValueError(
                f"Platform-specific dependency needs a formula condition: {requirement.name}"
            )
        matches = [
            package
            for package in packages
            if package["name"] == requirement.name.lower().replace("_", "-")
            and package["version"] in requirement.specifier
        ]
        if len(matches) != 1:
            raise ValueError(f"Expected one locked source for {requirement.name}")
        package = matches[0]
        source = package["sdist"]
        if not source["url"].startswith(
            "https://files.pythonhosted.org/packages/"
        ) or not re.fullmatch(r"sha256:[0-9a-f]{64}", source["hash"]):
            raise ValueError("Dependency source must have a public PyPI URL and SHA-256")
        selected.append(package)
    return sorted(selected, key=lambda package: package["name"])


def formula(version: str, source: Path, resources: list[dict], *, local: bool = False) -> str:
    url = (
        source.resolve().as_uri()
        if local
        else (
            f"https://github.com/reunionstudio/snowbeam/releases/download/v{version}/{source.name}"
        )
    )
    checksum = hashlib.sha256(source.read_bytes()).hexdigest()
    text = f'''# Generated by tools/homebrew_formula.py; do not edit dependency resources by hand.
class Snowbeam < Formula
  include Language::Python::Virtualenv

  desc "Snowflake connections and individual agent access in your terminal"
  homepage "https://reunionstudio.io/snowbeam.html"
  url "{url}"
  version "{version}"
  sha256 "{checksum}"
  license "MIT"

  env :std

  depends_on "python@3.13"
'''
    for package in resources:
        source_data = package["sdist"]
        text += f'''
  resource "{package["name"]}" do
    url "{source_data["url"]}"
    sha256 "{source_data["hash"].removeprefix("sha256:")}"
  end
'''
    return (
        text
        + """
  def install
    virtualenv_install_with_resources(using: "python3.13")
  end

  def caveats
    <<~EOS
      Run snowbeam in your terminal. Live checks also require Snowflake CLI (snow).
      Install and authorize your chosen vault CLI separately.
      In Snowbeam, use Updates > Update and restart when a new release is available.
      Manual alternative: quit Snowbeam, then brew upgrade reunionstudio/tap/snowbeam.
      Configuration and cached inventory remain in your user directory.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/snowbeam --version")
    inventory = JSON.parse(shell_output("#{bin}/snowbeam --demo inventory --json"))
    refute_empty inventory.fetch("accounts")
    refute_empty inventory.fetch("connections")
    updates = JSON.parse(shell_output("#{bin}/snowbeam --demo updates --json"))
    assert_equal false, updates.fetch("automatic")
  end
end
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", nargs="?", type=Path, default=Path("dist"))
    parser.add_argument(
        "--local", action="store_true", help="Use a local archive URL for testing only"
    )
    args = parser.parse_args()
    version = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]["version"]
    archive = args.directory / f"snowbeam-{version}.tar.gz"
    sums = (args.directory / "SHA256SUMS").read_text().splitlines()
    expected = f"{hashlib.sha256(archive.read_bytes()).hexdigest()}  {archive.name}"
    if expected not in sums:
        raise ValueError("Run check_release.py successfully before generating the formula")
    destination = args.directory / ("homebrew-local" if args.local else "homebrew") / "snowbeam.rb"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(formula(version, archive, runtime_resources(), local=args.local))
    print(destination)


if __name__ == "__main__":
    main()
